apiVersion: apps/v1
kind: Deployment
metadata:
  name: dswu
spec:
  replicas: 1
  selector:
    matchLabels:
      app:dswu
  template:
    metadata:
      labels:
        app: dswu
    spec:
      containers:
      - image: okteto.dev/dswu:latest
        name: dswu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "16b780b8-057d-11ed-b939-0242ac120002"
        - name: Vless_Path
          value: "/vldhyt55"
        - name: Vmess_UUID
          value: "16b780b8-057d-11ed-b939-0242ac120002"
        - name: Vmess_Path
          value: "/vm6dhts"
        - name: Share_Path
          value: "/v2link"
